nome = str(input('Digite seu nome ')).strip()
dividido = nome.split()
#troca = nome.replace(' ','')
print('Com todas as letras maiúsculas fica {}'.format(nome.upper()))
print('Com todas as letras minúsculas fica {}'.format(nome.lower()))
print('Capitalizado fica {}'.format(nome.capitalize()))
print('Como um título fica {}'.format(nome.title()))
print('O primeiro nome ({})'.format(dividido[0]),'tem {} letras'.format(len(dividido[0])))
print('Esse nome tem o total de {} letras sem contar os espaços'.format(len(nome)-nome.count(' ')))